apiVersion: v1
kind: Namespace
metadata:
  name: qenex-os
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qenex-core
  namespace: qenex-os
  labels:
    app: qenex-os
    component: core
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qenex-os
      component: core
  template:
    metadata:
      labels:
        app: qenex-os
        component: core
    spec:
      containers:
      - name: qenex-core
        image: qenex/os:latest
        ports:
        - containerPort: 8000
          name: api
        - containerPort: 80
          name: web
        env:
        - name: QENEX_MODE
          value: "production"
        - name: ENABLE_AI
          value: "true"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: qenex-service
  namespace: qenex-os
spec:
  selector:
    app: qenex-os
    component: core
  ports:
  - port: 80
    targetPort: 80
    name: web
  - port: 8000
    targetPort: 8000
    name: api
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: qenex-hpa
  namespace: qenex-os
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qenex-core
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qenex-config
  namespace: qenex-os
data:
  config.yaml: |
    system:
      mode: production
      auto_heal: true
      ai_enabled: true
    monitoring:
      interval: 60
      retention: 30d
    api:
      port: 8000
      auth: true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qenex-data
  namespace: qenex-os
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi